# 🫁 Medical Clinical RAG — Google Colab

**Scope:** Allergic Diseases in Adults/kids → **Asthma**

**Guideline:** *Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)* — NICE NG245, published 27 November 2024.

This notebook implements an end-to-end medical RAG prototype:

- PDF ingestion with page-aware extraction
- **Structure-aware clinical chunking** based on NICE sections and recommendation IDs
- Chunk metadata for section, recommendation, population, source and page
- Biomedical embeddings with MedCPT
- FAISS dense retrieval
- BM25 lexical retrieval
- Hybrid retrieval + score fusion
- MMR diversification
- Scope-aware clinical guardrails
- Optional LLM answer generation
- Citation and numerical consistency checks
- Asthma-specific retrieval test set

> ⚠️ This is a research/hackathon prototype, not a clinical decision-support system. It must not be used as a substitute for professional medical assessment.

In [2]:
# 1) Install dependencies
!pip -q install pymupdf faiss-cpu rank-bm25 sentence-transformers transformers accelerate openai pandas numpy scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.8/25.8 MB 44.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 51.1 MB/s eta 0:00:00

In [3]:
# 2) Upload the medical PDF
from google.colab import files
from pathlib import Path

uploaded = files.upload()

PDF_PATH = next(
    (name for name in uploaded.keys() if name.lower().endswith(".pdf")),
    None
)

if PDF_PATH is None:
    raise ValueError("Please upload a PDF clinical guideline.")

print("Using:", PDF_PATH)

Saving asthma-diagnosis-monitoring-and-chronic-asthma-management-bts-nice-sign-pdf-66143958279109.pdf to asthma-diagnosis-monitoring-and-chronic-asthma-management-bts-nice-sign-pdf-66143958279109.pdf
Using: asthma-diagnosis-monitoring-and-chronic-asthma-management-bts-nice-sign-pdf-66143958279109.pdf

In [4]:
# 3) Imports and configuration
import re
import json
import math
import numpy as np
import pandas as pd
import fitz

from pathlib import Path
from rank_bm25 import BM25Okapi
from IPython.display import display, Markdown

DOCUMENT_ID = "NICE_NG245"
DOCUMENT_TITLE = "Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)"
SOURCE_AUTHORITY = "NICE / BTS / SIGN"
POPULATION = "Adults, young people and children (age-specific recommendations apply)"
CLINICAL_FIELD = "Allergic Diseases"
CONDITION = "Asthma"
SOURCE_URL = "https://www.nice.org.uk/guidance/ng245"

# Research-informed clinical chunk configuration.
# For structured clinical guidelines, logical boundaries are more important
# than blindly using a fixed character window.
MAX_CHUNK_TOKENS = 450
CHUNK_OVERLAP_TOKENS = 0

# Retrieval configuration
DENSE_TOP_K = 30
BM25_TOP_K = 30
FINAL_TOP_K = 6
MMR_LAMBDA = 0.70

print("Configuration loaded.")
print(f"Scope: {CLINICAL_FIELD} → {CONDITION}")
print(f"Guideline: {DOCUMENT_ID}")

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.
Configuration loaded.
Scope: Allergic Diseases → Asthma
Guideline: NICE_NG245

## 1. PDF ingestion

The parser preserves page numbers and avoids destructive cleaning. Clinical numbers, units, negations, medication names, and recommendation wording are intentionally retained.

In [5]:
# 4) Extract page-aware text
def normalize_clinical_text(text: str) -> str:
    text = text.replace("\u00ad", "")
    text = re.sub(r"-\n", "", text)       # repair line-break hyphenation
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()

raw_pages = []

pdf = fitz.open(PDF_PATH)

for page_num, page in enumerate(pdf, start=1):
    text = normalize_clinical_text(page.get_text("text"))
    if text:
        raw_pages.append({
            "page": page_num,
            "text": text
        })

print(f"Pages extracted: {len(raw_pages)}")
print("First page preview:")
print(raw_pages[0]["text"][:1200])

Pages extracted: 64
First page preview:
Asthma: diagnosis,
monitoring and chronic
asthma management (BTS,
NICE, SIGN)
NICE guideline
Published: 27 November 2024
www.nice.org.uk/guidance/ng245
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights).

## 2. Research-informed clinical chunking

The scope is a single NICE/BTS/SIGN asthma guideline. The chunker therefore uses the **document's own clinical structure** rather than treating the PDF as generic prose.

### Chunking design used here

1. **Section-aware:** detect headings such as `1.1 Initial clinical assessment`, `1.5 Monitoring asthma control`, and `1.7 Pharmacological management in people aged 12 and over`.
2. **Recommendation-aware:** detect numbered recommendations such as `1.1.1`, `1.2.1`, `1.7.3`, etc.
3. **Atomic recommendation principle:** keep a complete recommendation together whenever it fits the embedding limit.
4. **Long-recommendation fallback:** only long recommendations are split at sentence boundaries.
5. **Context enrichment:** each chunk stores the section, recommendation ID, page, population and source metadata. This avoids losing meaning when a retrieved chunk is viewed independently.
6. **No artificial overlap by default:** the guideline already provides strong semantic boundaries. Recent RAG research reports that overlap can increase indexing cost without reliably improving QA, while clinical RAG reviews recommend adapting chunk granularity to corpus structure.
7. **Size target:** 450 approximate tokens keeps chunks comfortably below the 512-token MedCPT input limit while leaving room for section context.

This is preferable here to a generic `RecursiveCharacterTextSplitter`, because NICE recommendations are meaningful clinical units and splitting them in the middle of a recommendation can separate conditions, thresholds, exceptions, or age groups.

In [6]:
# 5) Structure-aware asthma guideline chunking

# Examples:
#   1.1 Initial clinical assessment
#   1.2 Objective tests for diagnosing asthma...
#   1.7 Pharmacological management in people aged 12 and over
SECTION_RE = re.compile(
    r"(?m)^\s*(1\.\d+(?:\.\d+)?)\s+(.+?)\s*$"
)

# NICE recommendation IDs in this guideline are normally 3-part IDs:
# 1.1.1, 1.2.1, 1.7.10, etc.
RECOMMENDATION_RE = re.compile(
    r"(?m)(?<!\d)(\d+\.\d+\.\d+)\s+"
)

def token_count(text):
    """Lightweight token approximation used only for chunk sizing."""
    return max(1, len(re.findall(r"\S+", text)))

def split_by_sentences(text, max_tokens=MAX_CHUNK_TOKENS):
    """Split long clinical material without arbitrary character cuts."""
    sentences = re.split(r"(?<=[.!?])\s+", text.strip())
    chunks = []
    current = []

    for sentence in sentences:
        if not sentence:
            continue

        candidate = " ".join(current + [sentence])

        if current and token_count(candidate) > max_tokens:
            chunks.append(" ".join(current).strip())
            current = [sentence]
        else:
            current.append(sentence)

    if current:
        chunks.append(" ".join(current).strip())

    return [c for c in chunks if c]

def current_section_before(text, position):
    """Return the most recent NICE section heading before a position."""
    matches = list(SECTION_RE.finditer(text[:position]))
    if not matches:
        return {
            "section_id": "general",
            "section_title": "General guideline context"
        }

    m = matches[-1]
    return {
        "section_id": m.group(1),
        "section_title": m.group(2).strip()
    }

def infer_population(section_title, text):
    """Attach age/population metadata where the guideline explicitly signals it."""
    s = (section_title + " " + text).lower()

    if "children under 5" in s:
        return "Children under 5"
    if "children aged 5 to 11" in s:
        return "Children aged 5 to 11"
    if "children aged 5 to 16" in s:
        return "Children aged 5 to 16"
    if "aged 12 and over" in s:
        return "People aged 12 and over"
    if "adolescents" in s:
        return "Adolescents"
    if "pregnancy" in s or "breastfeeding" in s:
        return "People with asthma during pregnancy/breastfeeding"
    if "adults" in s:
        return "Adults"

    return POPULATION

def add_chunk(
    chunks,
    counter,
    text,
    page,
    section,
    recommendation_id,
    population
):
    text = text.strip()
    if not text:
        return counter

    counter += 1

    # Add a compact contextual prefix for embedding/retrieval while retaining
    # the original guideline wording in the metadata fields.
    context_prefix = (
        f"Condition: {CONDITION}. "
        f"Section {section['section_id']}: {section['section_title']}. "
        f"Population: {population}. "
        f"Recommendation: {recommendation_id}. "
    )

    indexed_text = context_prefix + text

    chunks.append({
        "chunk_id": f"{DOCUMENT_ID}_p{page}_{counter:04d}",
        "text": indexed_text,
        "source_text": text,
        "page": page,
        "section_id": section["section_id"],
        "section": section["section_title"],
        "recommendation_id": recommendation_id,
        "document_id": DOCUMENT_ID,
        "document_type": "clinical_guideline",
        "clinical_field": CLINICAL_FIELD,
        "condition": CONDITION,
        "source_authority": SOURCE_AUTHORITY,
        "population": population,
        "title": DOCUMENT_TITLE,
        "source_url": SOURCE_URL
    })

    return counter

def make_chunks(pages):
    chunks = []
    chunk_counter = 0

    for page in pages:
        text = page["text"]

        # Find recommendation boundaries. A recommendation is treated as the
        # primary retrieval unit because it is a clinically meaningful statement.
        matches = list(RECOMMENDATION_RE.finditer(text))

        if not matches:
            # Pages such as contents/overview/definitions/rationale may not
            # contain numbered recommendations. Keep their semantic sections.
            section = current_section_before(text, len(text))
            population = infer_population(section["section_title"], text)

            for part in split_by_sentences(text):
                chunk_counter = add_chunk(
                    chunks,
                    chunk_counter,
                    part,
                    page["page"],
                    section,
                    "general",
                    population
                )
            continue

        # Material before the first recommendation.
        if matches[0].start() > 0:
            pre = text[:matches[0].start()].strip()

            if pre:
                section = current_section_before(text, matches[0].start())
                population = infer_population(section["section_title"], pre)

                for part in split_by_sentences(pre):
                    chunk_counter = add_chunk(
                        chunks,
                        chunk_counter,
                        part,
                        page["page"],
                        section,
                        "general",
                        population
                    )

        # Recommendation-level chunks.
        for i, match in enumerate(matches):
            start = match.start()
            end = matches[i + 1].start() if i + 1 < len(matches) else len(text)

            rec_id = match.group(1)
            rec_text = text[start:end].strip()

            section = current_section_before(text, start)
            population = infer_population(section["section_title"], rec_text)

            if token_count(rec_text) <= MAX_CHUNK_TOKENS:
                chunk_counter = add_chunk(
                    chunks,
                    chunk_counter,
                    rec_text,
                    page["page"],
                    section,
                    rec_id,
                    population
                )
            else:
                # Only long recommendations are sentence-split.
                parts = split_by_sentences(rec_text)

                for part in parts:
                    chunk_counter = add_chunk(
                        chunks,
                        chunk_counter,
                        part,
                        page["page"],
                        section,
                        rec_id,
                        population
                    )

    return chunks

chunks = make_chunks(raw_pages)

chunk_df = pd.DataFrame(chunks)

print("Chunks:", len(chunks))
print("Mean approximate tokens:", round(chunk_df["text"].map(token_count).mean(), 1))
print("Max approximate tokens:", chunk_df["text"].map(token_count).max())
print("Recommendation chunks:", (chunk_df["recommendation_id"] != "general").sum())

display(
    chunk_df.head(12)[[
        "chunk_id",
        "page",
        "section",
        "recommendation_id",
        "population",
        "text"
    ]]
)

Chunks: 175
Mean approximate tokens: 117.2
Max approximate tokens: 465
Recommendation chunks: 111

,chunk_id,page,section,recommendation_id,population,text
0,NICE_NG245_p1_0001,1,General guideline context,general,"Adults, young people and children (age-specifi...",Condition: Asthma. Section general: General gu...
1,NICE_NG245_p2_0002,2,General guideline context,general,"Adults, young people and children (age-specifi...",Condition: Asthma. Section general: General gu...
2,NICE_NG245_p3_0003,3,Organisation and delivery of care ...............,general,Children under 5,Condition: Asthma. Section 1.16: Organisation ...
3,NICE_NG245_p4_0004,4,General guideline context,general,Children under 5,Condition: Asthma. Section general: General gu...
4,NICE_NG245_p5_0005,5,General guideline context,general,Adults,Condition: Asthma. Section general: General gu...
5,NICE_NG245_p6_0006,6,General guideline context,general,"Adults, young people and children (age-specifi...",Condition: Asthma. Section general: General gu...
6,NICE_NG245_p7_0007,7,General guideline context,general,"Adults, young people and children (age-specifi...",Condition: Asthma. Section general: General gu...
7,NICE_NG245_p8_0008,8,Initial clinical assessment,general,"Adults, young people and children (age-specifi...",Condition: Asthma. Section 1.1: Initial clinic...
8,NICE_NG245_p8_0009,8,Initial clinical assessment,1.1.1,Adults,Condition: Asthma. Section 1.1: Initial clinic...
9,NICE_NG245_p8_0010,8,Obtain a structured clinical history in people...,1.1.2,"Adults, young people and children (age-specifi...",Condition: Asthma. Section 1.1.1: Obtain a str...
10,NICE_NG245_p8_0011,8,Do not confirm a diagnosis of asthma without a...,1.1.3,"Adults, young people and children (age-specifi...",Condition: Asthma. Section 1.1.2: Do not confi...
11,NICE_NG245_p9_0012,9,General guideline context,general,"Adults, young people and children (age-specifi...",Condition: Asthma. Section general: General gu...

## 🔬 Why this chunking strategy?

The chunking choice is based on recent RAG and clinical-RAG research:

- A 2026 systematic chunking analysis found sentence-based chunking to be cost-effective and reported that overlap did not provide a measurable benefit in its evaluated setting.
- A systematic review of biomedical RAG recommends optimizing chunk granularity according to the structure of the clinical corpus; it specifically notes that fixed-length chunking can fragment related information and recommends combining structural/sparse metadata with dense retrieval.
- A 2025 clinical decision-support comparison found adaptive/logical-boundary chunking improved retrieval and clinical-answer quality over a fixed baseline.

For this NICE guideline, the most defensible implementation is therefore **recommendation-aware + section-aware chunking**, with metadata preservation and no forced overlap. The notebook can later compare this against recursive/fixed chunking using the same retrieval and evaluation pipeline.

## 3. Medical embeddings

MedCPT is used because this is a biomedical/clinical retrieval task. The article encoder indexes guideline chunks and the query encoder embeds user questions.

The chunking stage keeps each retrieval unit clinically coherent before embedding it.

In [7]:
# 6) Load biomedical embedding model
from transformers import AutoTokenizer, AutoModel
import torch

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

QUERY_MODEL_NAME = "ncbi/MedCPT-Query-Encoder"
ARTICLE_MODEL_NAME = "ncbi/MedCPT-Article-Encoder"

query_tokenizer = AutoTokenizer.from_pretrained(QUERY_MODEL_NAME)
query_model = AutoModel.from_pretrained(QUERY_MODEL_NAME).to(DEVICE)

article_tokenizer = AutoTokenizer.from_pretrained(ARTICLE_MODEL_NAME)
article_model = AutoModel.from_pretrained(ARTICLE_MODEL_NAME).to(DEVICE)

query_model.eval()
article_model.eval()

def mean_pool(output, attention_mask):
    token_embeddings = output.last_hidden_state
    mask = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()
    return (token_embeddings * mask).sum(dim=1) / mask.sum(dim=1).clamp(min=1e-9)

@torch.no_grad()
def encode_texts(texts, tokenizer, model, batch_size=16):
    all_embeddings = []

    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        inputs = tokenizer(
            batch,
            padding=True,
            truncation=True,
            max_length=512,
            return_tensors="pt"
        ).to(DEVICE)

        outputs = model(**inputs)
        emb = mean_pool(outputs, inputs["attention_mask"])
        emb = torch.nn.functional.normalize(emb, p=2, dim=1)
        all_embeddings.append(emb.cpu().numpy())

    return np.vstack(all_embeddings)

def encode_query(query):
    return encode_texts(
        [query],
        query_tokenizer,
        query_model,
        batch_size=1
    )[0]

texts = [c["text"] for c in chunks]
embeddings = encode_texts(texts, article_tokenizer, article_model)

print("Embedding matrix:", embeddings.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.49k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/226k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/706k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/74.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.49k [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/226k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/706k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/74.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Embedding matrix: (175, 768)

## 4. FAISS + BM25 hybrid retrieval

In [8]:
# 7) Build dense FAISS index and BM25 index
import faiss

dimension = embeddings.shape[1]

faiss_index = faiss.IndexFlatIP(dimension)
faiss_index.add(embeddings.astype("float32"))

bm25_corpus = [c["text"].lower().split() for c in chunks]
bm25 = BM25Okapi(bm25_corpus)

print("FAISS vectors:", faiss_index.ntotal)
print("BM25 documents:", len(bm25_corpus))

FAISS vectors: 175
BM25 documents: 175

In [9]:
# 8) Hybrid retrieval + metadata filtering + MMR
# Metadata filters are asthma-specific and preserve age/section provenance.
def minmax(values):
    values = np.asarray(values, dtype=float)
    if len(values) == 0:
        return values
    lo, hi = values.min(), values.max()
    if hi - lo < 1e-9:
        return np.ones_like(values)
    return (values - lo) / (hi - lo)

def cosine_sim(a, b):
    return float(np.dot(a, b))

def mmr_select(query_embedding, candidate_indices, relevance_scores, k=FINAL_TOP_K, lambda_mult=MMR_LAMBDA):
    selected = []
    remaining = list(candidate_indices)

    while remaining and len(selected) < k:
        best_idx = None
        best_value = -1e9

        for idx in remaining:
            relevance = relevance_scores[idx]

            if not selected:
                diversity_penalty = 0.0
            else:
                diversity_penalty = max(
                    cosine_sim(embeddings[idx], embeddings[j])
                    for j in selected
                )

            value = (
                lambda_mult * relevance
                - (1 - lambda_mult) * diversity_penalty
            )

            if value > best_value:
                best_value = value
                best_idx = idx

        selected.append(best_idx)
        remaining.remove(best_idx)

    return selected

def hybrid_search(
    query,
    top_k=FINAL_TOP_K,
    condition=None,
    recommendation_id=None,
    population=None
):
    # Dense candidates
    q = encode_query(query).astype("float32").reshape(1, -1)
    dense_scores, dense_ids = faiss_index.search(
        q, min(DENSE_TOP_K, len(chunks))
    )

    dense_scores = dense_scores[0]
    dense_ids = dense_ids[0]

    # BM25 candidates
    bm_scores_all = bm25.get_scores(query.lower().split())
    bm_ids = np.argsort(bm_scores_all)[::-1][:min(BM25_TOP_K, len(chunks))]

    candidate_ids = set(int(i) for i in dense_ids if i >= 0)
    candidate_ids.update(int(i) for i in bm_ids)

    # Optional metadata/content filter
    filtered = []
    for idx in candidate_ids:
        item = chunks[idx]

        if recommendation_id is not None:
            if item["recommendation_id"] != recommendation_id:
                continue

        if condition is not None:
            if condition.lower() not in item["condition"].lower():
                continue

        if population is not None:
            if population.lower() not in item["population"].lower():
                continue

        filtered.append(idx)

    if not filtered:
        return []

    dense_map = {int(i): float(s) for i, s in zip(dense_ids, dense_scores)}
    bm_map = {int(i): float(bm_scores_all[i]) for i in bm_ids}

    dense_raw = np.array([dense_map.get(i, 0.0) for i in filtered])
    bm_raw = np.array([bm_map.get(i, 0.0) for i in filtered])

    dense_norm = minmax(dense_raw)
    bm_norm = minmax(bm_raw)

    # Weighted fusion: dense 65%, lexical 35%
    fused = 0.65 * dense_norm + 0.35 * bm_norm
    score_map = {idx: float(score) for idx, score in zip(filtered, fused)}

    selected = mmr_select(
        q[0],
        filtered,
        score_map,
        k=top_k
    )

    results = []
    for idx in selected:
        item = dict(chunks[idx])
        item["dense_score"] = dense_map.get(idx, 0.0)
        item["bm25_score"] = bm_map.get(idx, 0.0)
        item["hybrid_score"] = score_map[idx]
        results.append(item)

    return results

def show_results(results):
    rows = []
    for r in results:
        rows.append({
            "page": r["page"],
            "recommendation": r["recommendation_id"],
            "hybrid_score": round(r["hybrid_score"], 4),
            "text": r["text"][:500]
        })
    display(pd.DataFrame(rows))

# Test retrieval
query = "What are the red flags that should prompt further investigation or referral for headache?"
results = hybrid_search(query)
show_results(results)

,page,recommendation,hybrid_score,text
0,58,general,0.9566,Condition: Asthma. Section general: General gu...
1,60,general,0.8274,Condition: Asthma. Section general: General gu...
2,46,general,0.8194,Condition: Asthma. Section general: General gu...
3,25,1.9.3,0.8103,Condition: Asthma. Section general: General gu...
4,8,general,0.6406,Condition: Asthma. Section 1.1: Initial clinic...
5,54,general,0.6443,Condition: Asthma. Section general: General gu...

## 5. Clinical safety guardrails

The system should not answer outside the current knowledge-base scope. It should also detect obvious red-flag language and avoid presenting the RAG output as a diagnosis or prescription.

In [10]:
# 9) Asthma-specific safety and scope gate

RED_FLAG_PATTERNS = [
    "acute asthma attack",
    "severe asthma attack",
    "difficulty breathing",
    "struggling to breathe",
    "cannot speak",
    "hospital admission",
    "emergency department",
    "acute exacerbation"
]

IN_SCOPE_TERMS = [
    "asthma",
    "wheeze",
    "wheezing",
    "breathlessness",
    "chest tightness",
    "cough",
    "fev1",
    "feno",
    "eosinophil",
    "peak expiratory flow",
    "pef",
    "spirometry",
    "bronchodilator reversibility",
    "inhaled corticosteroid",
    "ics",
    "formoterol",
    "mart",
    "air therapy",
    "saba",
    "laba",
    "lama",
    "ltra",
    "inhaler",
    "inhaler technique",
    "asthma control",
    "asthma action plan"
]

def safety_check(query):
    q = query.lower()

    red_flags = [p for p in RED_FLAG_PATTERNS if p in q]
    in_scope = any(term in q for term in IN_SCOPE_TERMS)

    return {
        "red_flags_detected": red_flags,
        "in_scope": in_scope,
        "scope": f"{CLINICAL_FIELD} → {CONDITION}",
        "population": POPULATION
    }

def build_context(results):
    blocks = []

    for i, r in enumerate(results, start=1):
        citation = (
            f"[NICE NG245 | Section {r['section_id']} | "
            f"Recommendation {r['recommendation_id']} | "
            f"Page {r['page']} | Population: {r['population']}]"
        )

        blocks.append(
            f"Evidence {i} {citation}\n{r['source_text']}"
        )

    return "\n\n---\n\n".join(blocks)

def citation_for(r):
    return (
        f"[NICE NG245, Section {r['section_id']}, "
        f"Recommendation {r['recommendation_id']}, p.{r['page']}]"
    )

## 6. Optional LLM answer generation

This cell uses an OpenAI API key entered privately in Colab. The LLM is instructed to answer only from retrieved evidence and to cite each clinical claim.

If you do not have an API key, the notebook still works as a retrieval system and displays the evidence chunks.

In [11]:
# 10) Optional LLM generation
from getpass import getpass

USE_LLM = False

if USE_LLM:
    from openai import OpenAI

    OPENAI_API_KEY = getpass("Enter OPENAI_API_KEY: ")
    client = OpenAI(api_key=OPENAI_API_KEY)

SYSTEM_PROMPT = '''
You are a clinical evidence retrieval assistant for an asthma guideline.

Scope:
- Clinical field: Allergic Diseases
- Condition: Asthma
- Source: Asthma: diagnosis, monitoring and chronic asthma management
  (BTS, NICE, SIGN), NICE NG245
- Population: adults, young people and children, with age-specific
  recommendations preserved.

Use ONLY the supplied retrieved evidence.
Do not invent clinical facts, recommendations, dosages, contraindications,
age groups, or citations.
Do not diagnose a patient.
Do not prescribe individualized treatment.
Preserve all numerical values exactly.
Preserve negative recommendations such as "do not".
If the evidence is insufficient, say that the available source does not
provide enough information.

Every clinically relevant claim must include a citation in this format:
[NICE NG245, Section X.X, Recommendation X.X.X, p.X]

This is guideline information, not individualized medical advice.
'''

def answer_query(query, use_llm=USE_LLM):
    safety = safety_check(query)

    if not safety["in_scope"]:
        return {
            "answer": (
                "The current knowledge base is scoped to asthma guidance "
                "within allergic diseases for adults, young people and "
                "children. The available source does not provide enough "
                "information to answer this question reliably."
            ),
            "sources": []
        }

    results = hybrid_search(query, condition=CONDITION)

    if not results:
        return {
            "answer": "No sufficiently relevant asthma guideline evidence was retrieved.",
            "sources": []
        }

    context = build_context(results)

    # Safe fallback: evidence-only response
    if not use_llm:
        return {
            "answer": (
                "LLM generation is disabled. The following NICE NG245 "
                "guideline evidence was retrieved for the query:"

 + context
            ),
            "sources": results
        }

    user_prompt = f'''
Clinical evidence:
{context}

User question:
{query}

Answer only from the evidence above. Include precise citations.
'''

    response = client.chat.completions.create(
        model="gpt-5.6",
        temperature=0,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_prompt}
        ]
    )

    return {
        "answer": response.choices[0].message.content,
        "sources": results
    }

# Example
response = answer_query(
    "What objective tests are used to diagnose asthma in adults?",
    use_llm=False
)

print(response["answer"])

LLM generation is disabled. The following NICE NG245 guideline evidence was retrieved for the query:Evidence 1 [NICE NG245 | Section 1.1.6 | Recommendation 1.1.7 | Page 9 | Population: Children aged 5 to 16]
1.1.7
Be aware that the results of spirometry and FeNO tests may be affected in people
who have been treated with inhaled corticosteroids (the test results are more
likely to be normal). [NICE 2017]
1.2 Objective tests for diagnosing asthma in adults,
young people and children aged 5 to 16 with a
history suggestive of asthma
Adults
See also algorithm A for a summary of objective tests for diagnosing asthma in adults and
young people (aged over 16 years) with a history suggesting asthma.
Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights).
Page 9 of
64

---

Evidence 2 [NICE NG245 | Section 1.2.3 | Recommendation 1.2.4 | Page 10 | Population: Children aged 5 to 16]
1.2.4
If asthma is not confirmed by eosinophil count, FeNO, BDR or PEF variability but
still suspected on clinical grounds, refer for consideration of a bronchial challenge
test. Diagnose asthma if bronchial hyper-responsiveness is present. [BTS/NICE/
SIGN 2024]
Children aged 5 to 16
See also algorithm B for a summary of objective tests for diagnosing asthma in children
aged 5 to 16 with a history suggesting asthma.

---

Evidence 3 [NICE NG245 | Section 1.3 | Recommendation 1.3.1 | Page 13 | Population: Children under 5]
1.3.1
For children under 5 with suspected asthma, treat with inhaled corticosteroids in
line with the recommendations on medicines for initial management in children
under 5, and review the child on a regular basis. If they still have symptoms when
they reach 5 years, attempt objective tests (see the section on objective tests for
diagnosing asthma in adults, young people and children aged 5 to 16). [NICE
2017]

---

Evidence 4 [NICE NG245 | Section general | Recommendation general | Page 46 | Population: Children under 5]
In view of the difficulty in diagnosing asthma in this age group the committee also agreed
that any child who had been admitted to hospital, or been taken to the emergency
department twice or more, because of wheezing or breathlessness should be referred to a
specialist respiratory paediatrician for advice on diagnosis and management. How the recommendations might affect practice
The diagnostic tests recommended for both children and adults are not routinely carried
out in current practice, with the exception of spirometry and reversibility testing, which is
performed in some adults with suspected asthma. FeNO equipment is not available in
some areas, but an eosinophil count and IgE level is easily obtainable everywhere. Bronchial challenge tests are not done in primary care and infrequently used in secondary
care. The recommendations will increase the demand for challenge tests and initially there
will be a capacity problem. Incorporating the recommended diagnostic sequences into
clinical practice would therefore require significant investment. However, using the tests
increases the accuracy of asthma diagnosis and will be cost-effective over time. The recommendations for children under 5 are based on a pragmatic trial of treatment, as
is current practice. Return to recommendations
Monitoring asthma control
Recommendations

---

Evidence 5 [NICE NG245 | Section 1.3.2 | Recommendation 1.3.3 | Page 13 | Population: Adults, young people and children (age-specific recommendations apply)]
1.3.3
Refer to a specialist respiratory paediatrician any preschool child with an
admission to hospital, or 2 or more admissions to an emergency department, with
wheeze in a 12-month period. [BTS/NICE/SIGN 2024]
1.4 Diagnosing occupational asthma
See the BTS clinical statement on occupational asthma.

---

Evidence 6 [NICE NG245 | Section general | Recommendation general | Page 41 | Population: Children aged 5 to 16]
Rationale and impact
These sections briefly explain why the committee made the recommendations and how
they might affect practice. As this guideline applies to England and Scotland, the perspective was for both England
and Scotland. Objective tests for diagnosing asthma in adults,
young people and children aged 5 to 16 with a
history suggestive of asthma
Recommendations

## 7. Citation + numerical consistency checks

These checks are deliberately conservative. In a medical RAG system, a wrong citation or changed number should be treated as a failure rather than silently corrected.

In [12]:
# 11) Lightweight validation
def extract_numbers(text):
    return re.findall(
        r"(?<!\w)(?:\d+(?:\.\d+)?)(?:\s*[-–]\s*\d+(?:\.\d+)?)?",
        text
    )

def validate_citations(answer, sources):
    valid = {
        citation_for(r)
        for r in sources
    }

    found = re.findall(
        r"\[NICE NG245, Section [^\]]+, Recommendation [^\]]+, p\.\d+\]",
        answer
    )

    invalid = [c for c in found if c not in valid]

    return {
        "citations_found": found,
        "invalid_citations": invalid,
        "citation_valid": len(invalid) == 0
    }

def validate_numbers(answer, sources):
    source_text = " ".join(r["text"] for r in sources)
    answer_numbers = set(extract_numbers(answer))
    source_numbers = set(extract_numbers(source_text))

    unsupported = sorted(answer_numbers - source_numbers)

    return {
        "answer_numbers": sorted(answer_numbers),
        "unsupported_numbers": unsupported,
        "numeric_check": len(unsupported) == 0
    }

def validate_response(answer, sources):
    citation_result = validate_citations(answer, sources)
    number_result = validate_numbers(answer, sources)

    return {
        **citation_result,
        **number_result,
        "safe_to_display": (
            citation_result["citation_valid"]
            and number_result["numeric_check"]
        )
    }

# Example validation
if response["sources"]:
    validation = validate_response(
        response["answer"],
        response["sources"]
    )
    print(json.dumps(validation, indent=2))

{
  "citations_found": [],
  "invalid_citations": [],
  "citation_valid": true,
  "answer_numbers": [
    "1",
    "1.1",
    "1.2",
    "1.3",
    "1.4",
    "10",
    "12",
    "13",
    "16",
    "2",
    "2017",
    "2024",
    "2026",
    "3",
    "4",
    "41",
    "46",
    "5",
    "6",
    "64",
    "7",
    "9"
  ],
  "unsupported_numbers": [
    "10",
    "13",
    "41",
    "46"
  ],
  "numeric_check": false,
  "safe_to_display": false
}

## 8. Asthma retrieval test set

These tests are designed from the supplied NICE NG245 asthma guideline. They cover:
- initial clinical assessment
- objective diagnosis
- monitoring asthma control
- pharmacological management
- self-management
- risk-stratified care

They evaluate retrieval behavior; they do not claim clinical performance without a labeled benchmark.

In [13]:
# 12) Asthma retrieval evaluation examples
TEST_QUERIES = [
    "What clinical history should be obtained when asthma is suspected?",
    "What objective tests can diagnose asthma in adults?",
    "What are the FeNO and bronchodilator reversibility thresholds for diagnosing asthma?",
    "How should asthma control be monitored at every review?",
    "What is the initial treatment for newly diagnosed asthma in people aged 12 and over?",
    "What is the initial treatment for children aged 5 to 11 with newly diagnosed asthma?",
    "What should be checked before escalating asthma medicines?",
    "What should be included in an asthma self-management programme?",
    "Which people with asthma are at increased risk of poor outcomes?"
]

evaluation_rows = []

for q in TEST_QUERIES:
    retrieved = hybrid_search(
        q,
        top_k=6,
        condition=CONDITION
    )

    evaluation_rows.append({
        "query": q,
        "retrieved_chunks": len(retrieved),
        "top_recommendations": ", ".join(
            sorted(set(r["recommendation_id"] for r in retrieved))
        ),
        "top_sections": ", ".join(
            sorted(set(r["section_id"] for r in retrieved))
        ),
        "top_pages": ", ".join(str(r["page"]) for r in retrieved[:3])
    })

display(pd.DataFrame(evaluation_rows))

,query,retrieved_chunks,top_recommendations,top_sections,top_pages
0,What clinical history should be obtained when ...,6,"1.1.1, 1.1.2, 1.2.9, 1.3.2, 1.6.3, general","1.1, 1.1.1, 1.3.1, general","8, 41, 49"
1,What objective tests can diagnose asthma in ad...,6,"1.1.7, 1.2.4, 1.2.9, 1.3.1, 1.3.3, general","1.1.6, 1.2.3, 1.3, 1.3.2, general","10, 13, 9"
2,What are the FeNO and bronchodilator reversibi...,6,"1.2.2, general","1.2.1, general","42, 10, 46"
3,How should asthma control be monitored at ever...,6,"1.10.3, 1.14.5, 1.5.1, 1.5.2, 1.6.1, 1.6.7","1.10.2, 1.5, 1.5.1, 1.6.6, general","14, 14, 17"
4,What is the initial treatment for newly diagno...,6,"1.7.6, general","1.7, general","19, 18, 50"
5,What is the initial treatment for children age...,6,"1.3.1, 1.7.6, general","1.3, 1.9, general","55, 22, 58"
6,What should be checked before escalating asthm...,6,"1.14.4, 1.16.1, 1.6.1, 1.6.3, 1.6.7, general","1.14.3, 1.16, 1.6.6, general","54, 17, 49"
7,What should be included in an asthma self-mana...,6,"1.14.4, 1.14.5, 1.16.2, general","1.14.3, 1.14.4, 1.16.1, general","29, 40, 58"
8,Which people with asthma are at increased risk...,6,"1.1.4, 1.10.1, 1.14.5, 1.15.1, 1.16.1, 1.6.3","1.10, 1.15, 1.16, general","30, 49, 9"

## 9. Save the local vector/RAG artifacts

For a hackathon demo, this lets you avoid rebuilding embeddings every time the notebook is reopened. The files remain local to the current Colab runtime unless you copy them to Google Drive.

In [14]:
# 13) Save indexes and metadata
import pickle

faiss.write_index(faiss_index, "medical_rag.faiss")

with open("medical_rag_chunks.pkl", "wb") as f:
    pickle.dump(chunks, f)

np.save("medical_rag_embeddings.npy", embeddings)

print("Saved:")
print("- medical_rag.faiss")
print("- medical_rag_chunks.pkl")
print("- medical_rag_embeddings.npy")

Saved:
- medical_rag.faiss
- medical_rag_chunks.pkl
- medical_rag_embeddings.npy

# ✅ Asthma RAG demo

Change the question below and run the cell.

The pipeline is:

**Query → Asthma Scope/Safety Gate → MedCPT Dense Search + BM25 → Hybrid Fusion → MMR → NICE NG245 Evidence → Optional LLM → Citation/Numeric Validation**

In [15]:
# 14) Interactive demo

user_query = "What objective tests are recommended to diagnose asthma in adults?"

safety = safety_check(user_query)
print("\nSafety:", safety)

if safety["red_flags_detected"]:
    print(
        "\n⚠️ Red-flag language detected. "
        "The query should be handled with appropriate clinical urgency."
    )

demo = answer_query(user_query, use_llm=USE_LLM)

print("\nANSWER / EVIDENCE\n")
print(demo["answer"])

if demo["sources"]:
    print("\nSOURCES\n")
    for r in demo["sources"]:
        print(citation_for(r))

Safety: {'red_flags_detected': [], 'in_scope': True, 'scope': 'Allergic Diseases → Asthma', 'population': 'Adults, young people and children (age-specific recommendations apply)'}

ANSWER / EVIDENCE

LLM generation is disabled. The following NICE NG245 guideline evidence was retrieved for the query:Evidence 1 [NICE NG245 | Section 1.3 | Recommendation 1.3.1 | Page 13 | Population: Children under 5]
1.3.1
For children under 5 with suspected asthma, treat with inhaled corticosteroids in
line with the recommendations on medicines for initial management in children
under 5, and review the child on a regular basis. If they still have symptoms when
they reach 5 years, attempt objective tests (see the section on objective tests for
diagnosing asthma in adults, young people and children aged 5 to 16). [NICE
2017]

---

Evidence 2 [NICE NG245 | Section general | Recommendation general | Page 46 | Population: Children under 5]
In view of the difficulty in diagnosing asthma in this age group the committee also agreed
that any child who had been admitted to hospital, or been taken to the emergency
department twice or more, because of wheezing or breathlessness should be referred to a
specialist respiratory paediatrician for advice on diagnosis and management. How the recommendations might affect practice
The diagnostic tests recommended for both children and adults are not routinely carried
out in current practice, with the exception of spirometry and reversibility testing, which is
performed in some adults with suspected asthma. FeNO equipment is not available in
some areas, but an eosinophil count and IgE level is easily obtainable everywhere. Bronchial challenge tests are not done in primary care and infrequently used in secondary
care. The recommendations will increase the demand for challenge tests and initially there
will be a capacity problem. Incorporating the recommended diagnostic sequences into
clinical practice would therefore require significant investment. However, using the tests
increases the accuracy of asthma diagnosis and will be cost-effective over time. The recommendations for children under 5 are based on a pragmatic trial of treatment, as
is current practice. Return to recommendations
Monitoring asthma control
Recommendations

---

Evidence 3 [NICE NG245 | Section 1.3.2 | Recommendation 1.3.3 | Page 13 | Population: Adults, young people and children (age-specific recommendations apply)]
1.3.3
Refer to a specialist respiratory paediatrician any preschool child with an
admission to hospital, or 2 or more admissions to an emergency department, with
wheeze in a 12-month period. [BTS/NICE/SIGN 2024]
1.4 Diagnosing occupational asthma
See the BTS clinical statement on occupational asthma.

---

Evidence 4 [NICE NG245 | Section general | Recommendation general | Page 41 | Population: Children aged 5 to 16]
Rationale and impact
These sections briefly explain why the committee made the recommendations and how
they might affect practice. As this guideline applies to England and Scotland, the perspective was for both England
and Scotland. Objective tests for diagnosing asthma in adults,
young people and children aged 5 to 16 with a
history suggestive of asthma
Recommendations

---

Evidence 5 [NICE NG245 | Section general | Recommendation 1.2.9 | Page 41 | Population: Adults]
1.2.9
Why the committee made the recommendations
Although evidence on symptoms and signs of asthma was not reviewed for this guideline
update, the committee emphasised the importance of taking a good clinical history in all
their discussions of diagnosis. Evidence on objective tests was only included if it was
carried out in people in whom asthma was suspected on clinical grounds. Therefore, the
recommendations for diagnostic testing should only be applied when the history and
examination findings support a diagnosis of asthma. The committee also noted that,
depending on the mode of presentation, other diagnoses might be considered, but they
confined their recommendations to confirmation or exclusion of asthma.
The committee reviewed evidence on tests of variation in airflow obstruction and markers
of allergy separately for adults and children. They took into account the sensitivity and
specificity of the various tests but did not base their recommendations on these measures
alone. They noted that no test showed high enough values of both sensitivity and
specificity to be diagnostic in all cases. However, some of them showed high specificity
and were potentially useful as rule-in tests with a suitably high cut-off value. It was agreed
that a combination of tests would be needed for most people.
When considering combinations of tests, the extent to which the available tests correlate
with one another is important because there is less benefit in performing a test that gives
Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights).
Page 41 of
64

---

Evidence 6 [NICE NG245 | Section general | Recommendation general | Page 42 | Population: Adults]
similar information to a preceding one. Practical aspects were taken into account using the
committee's knowledge and experience. These included the availability of the tests, which
varies considerably (in particular, bronchial challenge testing is not available in primary
care and not readily available in secondary care), the ability of people to perform the tests,
and the acceptability of the tests to the person, which is particularly relevant in younger
children. The committee also considered the cost of the available tests. However, no health
economic study on the most cost-effective sequence or combination of tests was
identified. Therefore, a health economic model was developed to help address this. The committee discussed what cut-off values should be recommended for the tests. For
some of the tests it was agreed that it was inappropriate to state a numerical value for an
abnormal result. For example, normal ranges for blood tests may vary slightly between
laboratories. Therefore, for eosinophil counts and IgE levels, a raised measurement
(suggesting asthma) should be regarded as one above the upper end of the local
reference range. There are also several standardised methods of performing bronchial
challenge tests, and the definition of bronchial hyperresponsiveness will be dependent on
the method used. Spirometry should always be performed using an international standard protocol but the
method of expressing reversibility after bronchodilator varies. Ideally this would be based
on change in z-scores, but these are not measured by all spirometry equipment. Change in
absolute values of FEV1 is arguably best given as the percentage change compared with
the person's predicted FEV1, and using this parameter a change of 10% or more is
abnormal. Using the more traditional means of expressing the change as a percentage of
the baseline FEV1, increased reversibility would be 12% or more in adults and children. In
adults, the change should also be 200 ml or more. The committee agreed to include both
ways of measuring reversibility in its recommendations. An optimal cut-off value is also difficult to give for FeNO (fractional exhaled nitric oxide). There is good evidence that FeNO levels increase with age and with height, and ideally
normal ranges would be available which correct for these factors. However, there are
currently no standard charts and FeNO equipment does not give an age/height corrected
output. Although not ideal, the committee agreed that they need to suggest a simple cutoff value. And because FeNO is the first, and possibly the only, test in the recommended
sequences in both adults and children they agreed that the value should be reasonably
high so that it would be specific, acknowledging that this sacrifices a degree of sensitivity.

SOURCES

[NICE NG245, Section 1.3, Recommendation 1.3.1, p.13]
[NICE NG245, Section general, Recommendation general, p.46]
[NICE NG245, Section 1.3.2, Recommendation 1.3.3, p.13]
[NICE NG245, Section general, Recommendation general, p.41]
[NICE NG245, Section general, Recommendation 1.2.9, p.41]
[NICE NG245, Section general, Recommendation general, p.42]

In [16]:
# Test Questions 1-10: Answerable

questions = [
    "What FeNO level supports a diagnosis of asthma in adults?",

    "What FEV1 increase is required to diagnose asthma using bronchodilator reversibility in adults?",

    "How often should peak expiratory flow be measured when spirometry is unavailable or delayed?",

    "What PEF variability supports a diagnosis of asthma in adults?",

    "When should a person with suspected asthma be referred for a bronchial challenge test?",

    "What FeNO level supports a diagnosis of asthma in children aged 5 to 16?",

    "What should be done if a child under 5 cannot perform objective tests at age 5?",

    "What factors should be checked when monitoring asthma control at every review?",

    "Which validated symptom questionnaires can be considered during an asthma review?",

    "Should regular PEF monitoring be used routinely to assess asthma control?"
]

for i, user_query in enumerate(questions, 1):

    print("\n" + "=" * 80)
    print(f"QUESTION {i}")
    print("=" * 80)
    print(user_query)

    safety = safety_check(user_query)
    print("\nSafety:", safety)

    if safety["red_flags_detected"]:
        print(
            "\n⚠️ Red-flag language detected. "
            "The query should be handled with appropriate clinical urgency."
        )

    demo = answer_query(user_query, use_llm=USE_LLM)

    print("\nANSWER / EVIDENCE\n")
    print(demo["answer"])

    if demo["sources"]:
        print("\nSOURCES\n")
        for r in demo["sources"]:
            print(citation_for(r))

================================================================================
QUESTION 1
================================================================================
What FeNO level supports a diagnosis of asthma in adults?

Safety: {'red_flags_detected': [], 'in_scope': True, 'scope': 'Allergic Diseases → Asthma', 'population': 'Adults, young people and children (age-specific recommendations apply)'}

ANSWER / EVIDENCE

LLM generation is disabled. The following NICE NG245 guideline evidence was retrieved for the query:Evidence 1 [NICE NG245 | Section general | Recommendation general | Page 48 | Population: Adults]
circumstances. FeNO
The evidence showed that, in both adults and children, regular FeNO monitoring led to a
reduction in the number of asthma exacerbations. In children there was also a significant
improvement in lung function. In adults, the reduction in exacerbations was achieved
alongside an overall reduction in the dosage of maintenance ICS therapy. This was not the
case in children, but the studies in this age group were more likely to be conducted in
secondary or tertiary care, so it is likely that they had a higher maintenance therapy
requirement. The committee concluded that FeNO monitoring was cost-effective in adults but may not
be in children. It was not possible on the current evidence to say what the optimum
frequency of monitoring should be, but the committee agreed that an appropriate
opportunity would be to make a routine measurement at the person's regular review
(which will be an annual review for most people). The FeNO level is a proxy measure of airway inflammation. It can therefore be very useful
in determining how to adjust treatment, or as an indicator of treatment adherence, when a
person with asthma has poor symptom control. Conversely, when symptom control is
excellent and the possibility of reducing maintenance therapy arises, a normal FeNO level
provides helpful reassurance. The committee therefore agreed that a FeNO measurement
should be considered whenever a change in maintenance therapy might be appropriate. How the recommendations might affect practice
Asthma control questionnaires are already recommended as part of an annual review. Therefore, no change to practice is anticipated. The recommendations on pulmonary
function are expected to reduce the use of PEF monitoring. Measurement of FeNO is increasingly used in secondary care asthma clinics, but in
primary care only a minority of GP practices have on-site access to the test. Regular FeNO
monitoring represents a significant change in practice because most people with asthma
are managed in primary care. This change will also carry a cost. The committee noted that
FeNO measurement is also useful in diagnosing asthma (see section 1.2 on objective tests
for diagnosing asthma), and increased access to the test will therefore be of dual benefit. Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights). Page 48 of
64

---

Evidence 2 [NICE NG245 | Section 1.2.4 | Recommendation 1.2.5 | Page 10 | Population: Adults, young people and children (age-specific recommendations apply)]
1.2.5
Measure the FeNO level in children with a history suggestive of asthma. Diagnose
asthma if the FeNO level is 35 ppb or more. [BTS/NICE/SIGN 2024]

---

Evidence 3 [NICE NG245 | Section general | Recommendation general | Page 46 | Population: Children under 5]
In view of the difficulty in diagnosing asthma in this age group the committee also agreed
that any child who had been admitted to hospital, or been taken to the emergency
department twice or more, because of wheezing or breathlessness should be referred to a
specialist respiratory paediatrician for advice on diagnosis and management. How the recommendations might affect practice
The diagnostic tests recommended for both children and adults are not routinely carried
out in current practice, with the exception of spirometry and reversibility testing, which is
performed in some adults with suspected asthma. FeNO equipment is not available in
some areas, but an eosinophil count and IgE level is easily obtainable everywhere. Bronchial challenge tests are not done in primary care and infrequently used in secondary
care. The recommendations will increase the demand for challenge tests and initially there
will be a capacity problem. Incorporating the recommended diagnostic sequences into
clinical practice would therefore require significant investment. However, using the tests
increases the accuracy of asthma diagnosis and will be cost-effective over time. The recommendations for children under 5 are based on a pragmatic trial of treatment, as
is current practice. Return to recommendations
Monitoring asthma control
Recommendations

---

Evidence 4 [NICE NG245 | Section 1.2.5 | Recommendation 1.2.6 | Page 10 | Population: Adults, young people and children (age-specific recommendations apply)]
1.2.6
If the FeNO level is not raised, or if FeNO testing is not available, measure BDR
with spirometry. Diagnose asthma if the FEV1 increase is 12% or more from
baseline (or if the FEV1 increase is 10% or more of the predicted normal FEV1).
[BTS/NICE/SIGN 2024]

---

Evidence 5 [NICE NG245 | Section general | Recommendation 1.2.1 | Page 10 | Population: Adults]
1.2.1
Measure the blood eosinophil count or fractional exhaled nitric oxide (FeNO) level
in adults with a history suggestive of asthma. Diagnose asthma if the eosinophil
count is above the laboratory reference range or the FeNO level is 50 ppb or
more. [BTS/NICE/SIGN 2024]

---

Evidence 6 [NICE NG245 | Section general | Recommendation general | Page 43 | Population: Children under 5]
Cut-offs of 50 ppb in adults and 35 ppb in children were agreed. No evidence was available for diagnostic tests in children under 5. The age at which a
child can co-operate with tests will vary, but the committee agreed that it is usually
necessary to manage these children pragmatically based on symptoms and signs only. Adults
Several tests showed good specificity for asthma, with values over 80% for blood
eosinophils, FeNO (cut-off values 40-50 ppb), peak expiratory flow (PEF) variability,
bronchial challenge tests, and spirometry with bronchodilator reversibility. However,
sensitivity was poor for most of these, and only FeNO and bronchial challenge tests
showed values over 70%. Although bronchial challenge is the most accurate test, overall, it
is more costly than others and is less readily available. Using the health economic model, the most cost-effective diagnostic strategy was found
to be a gradual rule-in approach. It facilitates a positive diagnosis of asthma in a broad
population using relatively inexpensive tests and confines the more expensive bronchial
challenge tests to the end of the sequence. The committee agreed that a cheap and highly specific test to rule in asthma should start
the sequence. This should be either an eosinophil count or a FeNO measurement, but both
need care in interpretation. For example, a raised eosinophil count can occur for other
reasons including other allergic diseases, and FeNO is also affected by allergic diseases,
although only those that affect the airways. Both measurements are altered in smokers. However, if used correctly in the presence of a history suggesting asthma, they are good
rule-in tests. The second test in the sequence should be to measure spirometry with reversibility. This is
a more specific test than it is sensitive, but it represents a test of airway function to
complement a first test which reflects atopy and so both components of asthma will have
been assessed. The committee were aware that there can be delays in accessing spirometry and FeNO
testing, and it is hoped that access will improve. However, if these tests are not available
or there is a significant delay in obtaining them, the committee agreed it would be
reasonable to use PEF variability as a substitute rule-in test. Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights). Page 43 of
64

SOURCES

[NICE NG245, Section general, Recommendation general, p.48]
[NICE NG245, Section 1.2.4, Recommendation 1.2.5, p.10]
[NICE NG245, Section general, Recommendation general, p.46]
[NICE NG245, Section 1.2.5, Recommendation 1.2.6, p.10]
[NICE NG245, Section general, Recommendation 1.2.1, p.10]
[NICE NG245, Section general, Recommendation general, p.43]

================================================================================
QUESTION 2
================================================================================
What FEV1 increase is required to diagnose asthma using bronchodilator reversibility in adults?

Safety: {'red_flags_detected': [], 'in_scope': True, 'scope': 'Allergic Diseases → Asthma', 'population': 'Adults, young people and children (age-specific recommendations apply)'}

ANSWER / EVIDENCE

LLM generation is disabled. The following NICE NG245 guideline evidence was retrieved for the query:Evidence 1 [NICE NG245 | Section 1.2.1 | Recommendation 1.2.2 | Page 10 | Population: Adults, young people and children (age-specific recommendations apply)]
1.2.2
If asthma is not confirmed by eosinophil count or FeNO level, measure
bronchodilator reversibility (BDR) with spirometry. Diagnose asthma if the FEV1
increase is 12% or more and 200 ml or more from the pre-bronchodilator
measurement (or if the FEV1 increase is 10% or more of the predicted normal
FEV1). [BTS/NICE/SIGN 2024]

---

Evidence 2 [NICE NG245 | Section 1.2.5 | Recommendation 1.2.6 | Page 10 | Population: Adults, young people and children (age-specific recommendations apply)]
1.2.6
If the FeNO level is not raised, or if FeNO testing is not available, measure BDR
with spirometry. Diagnose asthma if the FEV1 increase is 12% or more from
baseline (or if the FEV1 increase is 10% or more of the predicted normal FEV1).
[BTS/NICE/SIGN 2024]

---

Evidence 3 [NICE NG245 | Section general | Recommendation general | Page 42 | Population: Adults]
similar information to a preceding one. Practical aspects were taken into account using the
committee's knowledge and experience. These included the availability of the tests, which
varies considerably (in particular, bronchial challenge testing is not available in primary
care and not readily available in secondary care), the ability of people to perform the tests,
and the acceptability of the tests to the person, which is particularly relevant in younger
children. The committee also considered the cost of the available tests. However, no health
economic study on the most cost-effective sequence or combination of tests was
identified. Therefore, a health economic model was developed to help address this. The committee discussed what cut-off values should be recommended for the tests. For
some of the tests it was agreed that it was inappropriate to state a numerical value for an
abnormal result. For example, normal ranges for blood tests may vary slightly between
laboratories. Therefore, for eosinophil counts and IgE levels, a raised measurement
(suggesting asthma) should be regarded as one above the upper end of the local
reference range. There are also several standardised methods of performing bronchial
challenge tests, and the definition of bronchial hyperresponsiveness will be dependent on
the method used. Spirometry should always be performed using an international standard protocol but the
method of expressing reversibility after bronchodilator varies. Ideally this would be based
on change in z-scores, but these are not measured by all spirometry equipment. Change in
absolute values of FEV1 is arguably best given as the percentage change compared with
the person's predicted FEV1, and using this parameter a change of 10% or more is
abnormal. Using the more traditional means of expressing the change as a percentage of
the baseline FEV1, increased reversibility would be 12% or more in adults and children. In
adults, the change should also be 200 ml or more. The committee agreed to include both
ways of measuring reversibility in its recommendations. An optimal cut-off value is also difficult to give for FeNO (fractional exhaled nitric oxide). There is good evidence that FeNO levels increase with age and with height, and ideally
normal ranges would be available which correct for these factors. However, there are
currently no standard charts and FeNO equipment does not give an age/height corrected
output. Although not ideal, the committee agreed that they need to suggest a simple cutoff value. And because FeNO is the first, and possibly the only, test in the recommended
sequences in both adults and children they agreed that the value should be reasonably
high so that it would be specific, acknowledging that this sacrifices a degree of sensitivity.

---

Evidence 4 [NICE NG245 | Section 1.14.3 | Recommendation 1.14.4 | Page 29 | Population: Adults]
1.14.4
For adults (aged 17 and over) who are using an inhaled corticosteroid (ICS) in a
single inhaler, offer an increased dose of ICS for 7 days, within a selfmanagement programme, when asthma control deteriorates. Clearly outline in the
person's asthma action plan how and when to do this, and what to do if
symptoms do not improve.
When increasing ICS treatment:
• consider quadrupling the regular ICS dose
• do not exceed the maximum licensed daily dose. [NICE 2017]

---

Evidence 5 [NICE NG245 | Section general | Recommendation general | Page 46 | Population: Children under 5]
In view of the difficulty in diagnosing asthma in this age group the committee also agreed
that any child who had been admitted to hospital, or been taken to the emergency
department twice or more, because of wheezing or breathlessness should be referred to a
specialist respiratory paediatrician for advice on diagnosis and management. How the recommendations might affect practice
The diagnostic tests recommended for both children and adults are not routinely carried
out in current practice, with the exception of spirometry and reversibility testing, which is
performed in some adults with suspected asthma. FeNO equipment is not available in
some areas, but an eosinophil count and IgE level is easily obtainable everywhere. Bronchial challenge tests are not done in primary care and infrequently used in secondary
care. The recommendations will increase the demand for challenge tests and initially there
will be a capacity problem. Incorporating the recommended diagnostic sequences into
clinical practice would therefore require significant investment. However, using the tests
increases the accuracy of asthma diagnosis and will be cost-effective over time. The recommendations for children under 5 are based on a pragmatic trial of treatment, as
is current practice. Return to recommendations
Monitoring asthma control
Recommendations

---

Evidence 6 [NICE NG245 | Section general | Recommendation general | Page 52 | Population: People aged 12 and over]
first treatment step in people aged 12 and over. This was unsurprising as the advantages
of this as initial therapy have only recently been recognised. The committee therefore had
to consider studies of people with asthma uncontrolled on other starting treatments, either
a SABA when used as needed as sole therapy or when used in addition to regular lowdose ICS. They reasoned that these people would be sufficiently similar to people who are
not controlled with as-needed AIR to allow recommendations to be made, but agreed that
further research comparing different add-on therapies to ICS/formoterol as needed would
be useful. The evidence showed that regular low-dose ICS/LABA plus SABA as needed was superior
to regular low-dose ICS plus SABA as needed. It produced greater improvements in lung
function, and a reduction in the number of exacerbations and the amount of reliever
therapy needed. Low-dose MART was also better than regular low-dose ICS plus SABA as
needed in reducing asthma exacerbations, and people on this treatment needed less
reliever therapy. When low-dose ICS/LABA plus SABA as needed was compared with low-dose MART, the
people using MART were found to have fewer exacerbations and hospital admissions. The
committee noted that it would be simpler for people who are already using an ICS/
formoterol inhaler to start the MART regimen than to convert to new inhalers. The
committee also considered the economic analysis done for this update and agreed that
the MART regimen would be a cost-effective use of resources compared with low-dose
ICS/LABA plus SABA as needed. If treatment with MART using a low-dose maintenance regimen does not provide adequate
asthma control, the committee agreed that increasing the maintenance element of MART
to moderate dose is the appropriate next step. Evidence supporting this was available
from studies comparing moderate dose MART with both regular moderate dose ICS/LABA
with SABA as reliever and with regular moderate dose ICS with SABA as reliever. MART
was superior in both comparisons, most notably in reducing severe asthma exacerbations. If treatment with MART using a moderate-dose maintenance regimen does not provide
adequate asthma control, the evidence on how best to increase treatment is less clear cut. People whose asthma is uncontrolled at this stage will be using additional doses of ICS/
formoterol for symptom relief and will effectively be on high-dose ICS. The committee
agreed that ideally both FeNO and the eosinophil level should be checked, as well as
carefully assessing whether the person is adhering to their prescribed treatment. If FeNO
or eosinophil count is raised despite good adherence to this level of ICS, the risk of
Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved.

SOURCES

[NICE NG245, Section 1.2.1, Recommendation 1.2.2, p.10]
[NICE NG245, Section 1.2.5, Recommendation 1.2.6, p.10]
[NICE NG245, Section general, Recommendation general, p.42]
[NICE NG245, Section 1.14.3, Recommendation 1.14.4, p.29]
[NICE NG245, Section general, Recommendation general, p.46]
[NICE NG245, Section general, Recommendation general, p.52]

================================================================================
QUESTION 3
================================================================================
How often should peak expiratory flow be measured when spirometry is unavailable or delayed?

Safety: {'red_flags_detected': [], 'in_scope': True, 'scope': 'Allergic Diseases → Asthma', 'population': 'Adults, young people and children (age-specific recommendations apply)'}

ANSWER / EVIDENCE

LLM generation is disabled. The following NICE NG245 guideline evidence was retrieved for the query:Evidence 1 [NICE NG245 | Section 1.2.2 | Recommendation 1.2.3 | Page 10 | Population: Adults, young people and children (age-specific recommendations apply)]
1.2.3
If spirometry is not available or it is delayed, measure peak expiratory flow (PEF)
twice daily for 2 weeks. Diagnose asthma if PEF variability (expressed as
amplitude percentage mean) is 20% or more. [BTS/NICE/SIGN 2024]

---

Evidence 2 [NICE NG245 | Section 1.1.4 | Recommendation 1.1.5 | Page 9 | Population: Adults, young people and children (age-specific recommendations apply)]
1.1.5
Treat people immediately if they are acutely unwell or highly symptomatic at
presentation, and perform objective tests that may help support a diagnosis of
asthma (for example, eosinophil count, fractional exhaled nitric oxide [FeNO],
spirometry or peak expiratory flow [PEF] before and after bronchodilator) if the
equipment is available. [NICE 2017, amended BTS/NICE/SIGN 2024]

---


In [21]:
# Test Questions 11-15: Paraphrased

questions = [
    "For an adult suspected of having asthma, what FeNO measurement would be high enough to support the diagnosis?",

    "If spirometry is delayed, what alternative measurement can be taken over a two-week period to help confirm asthma?",

    "If the initial tests do not confirm asthma but clinical suspicion remains, what further investigation can be considered?",

    "During a routine asthma review, what information about reliever medication use should be assessed?",

    "What types of questionnaires can help assess asthma symptoms during a clinical review?"
]

for i, user_query in enumerate(questions, 11):

    print("\n" + "=" * 80)
    print(f"QUESTION {i}")
    print("=" * 80)
    print(user_query)

    safety = safety_check(user_query)
    print("\nSafety:", safety)

    if safety["red_flags_detected"]:
        print(
            "\n⚠️ Red-flag language detected. "
            "The query should be handled with appropriate clinical urgency."
        )

    demo = answer_query(user_query, use_llm=USE_LLM)

    print("\nANSWER / EVIDENCE\n")
    print(demo["answer"])

    if demo["sources"]:
        print("\nSOURCES\n")
        for r in demo["sources"]:
            print(citation_for(r))

================================================================================
QUESTION 11
================================================================================
For an adult suspected of having asthma, what FeNO measurement would be high enough to support the diagnosis?

Safety: {'red_flags_detected': [], 'in_scope': True, 'scope': 'Allergic Diseases → Asthma', 'population': 'Adults, young people and children (age-specific recommendations apply)'}

ANSWER / EVIDENCE

LLM generation is disabled. The following NICE NG245 guideline evidence was retrieved for the query:Evidence 1 [NICE NG245 | Section general | Recommendation general | Page 42 | Population: Adults]
similar information to a preceding one. Practical aspects were taken into account using the
committee's knowledge and experience. These included the availability of the tests, which
varies considerably (in particular, bronchial challenge testing is not available in primary
care and not readily available in secondary care), the ability of people to perform the tests,
and the acceptability of the tests to the person, which is particularly relevant in younger
children. The committee also considered the cost of the available tests. However, no health
economic study on the most cost-effective sequence or combination of tests was
identified. Therefore, a health economic model was developed to help address this. The committee discussed what cut-off values should be recommended for the tests. For
some of the tests it was agreed that it was inappropriate to state a numerical value for an
abnormal result. For example, normal ranges for blood tests may vary slightly between
laboratories. Therefore, for eosinophil counts and IgE levels, a raised measurement
(suggesting asthma) should be regarded as one above the upper end of the local
reference range. There are also several standardised methods of performing bronchial
challenge tests, and the definition of bronchial hyperresponsiveness will be dependent on
the method used. Spirometry should always be performed using an international standard protocol but the
method of expressing reversibility after bronchodilator varies. Ideally this would be based
on change in z-scores, but these are not measured by all spirometry equipment. Change in
absolute values of FEV1 is arguably best given as the percentage change compared with
the person's predicted FEV1, and using this parameter a change of 10% or more is
abnormal. Using the more traditional means of expressing the change as a percentage of
the baseline FEV1, increased reversibility would be 12% or more in adults and children. In
adults, the change should also be 200 ml or more. The committee agreed to include both
ways of measuring reversibility in its recommendations. An optimal cut-off value is also difficult to give for FeNO (fractional exhaled nitric oxide). There is good evidence that FeNO levels increase with age and with height, and ideally
normal ranges would be available which correct for these factors. However, there are
currently no standard charts and FeNO equipment does not give an age/height corrected
output. Although not ideal, the committee agreed that they need to suggest a simple cutoff value. And because FeNO is the first, and possibly the only, test in the recommended
sequences in both adults and children they agreed that the value should be reasonably
high so that it would be specific, acknowledging that this sacrifices a degree of sensitivity.

---

Evidence 2 [NICE NG245 | Section general | Recommendation general | Page 48 | Population: Adults]
circumstances. FeNO
The evidence showed that, in both adults and children, regular FeNO monitoring led to a
reduction in the number of asthma exacerbations. In children there was also a significant
improvement in lung function. In adults, the reduction in exacerbations was achieved
alongside an overall reduction in the dosage of maintenance ICS therapy. This was not the
case in children, but the studies in this age group were more likely to be conducted in
secondary or tertiary care, so it is likely that they had a higher maintenance therapy
requirement. The committee concluded that FeNO monitoring was cost-effective in adults but may not
be in children. It was not possible on the current evidence to say what the optimum
frequency of monitoring should be, but the committee agreed that an appropriate
opportunity would be to make a routine measurement at the person's regular review
(which will be an annual review for most people). The FeNO level is a proxy measure of airway inflammation. It can therefore be very useful
in determining how to adjust treatment, or as an indicator of treatment adherence, when a
person with asthma has poor symptom control. Conversely, when symptom control is
excellent and the possibility of reducing maintenance therapy arises, a normal FeNO level
provides helpful reassurance. The committee therefore agreed that a FeNO measurement
should be considered whenever a change in maintenance therapy might be appropriate. How the recommendations might affect practice
Asthma control questionnaires are already recommended as part of an annual review. Therefore, no change to practice is anticipated. The recommendations on pulmonary
function are expected to reduce the use of PEF monitoring. Measurement of FeNO is increasingly used in secondary care asthma clinics, but in
primary care only a minority of GP practices have on-site access to the test. Regular FeNO
monitoring represents a significant change in practice because most people with asthma
are managed in primary care. This change will also carry a cost. The committee noted that
FeNO measurement is also useful in diagnosing asthma (see section 1.2 on objective tests
for diagnosing asthma), and increased access to the test will therefore be of dual benefit. Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights). Page 48 of
64

---

Evidence 3 [NICE NG245 | Section general | Recommendation general | Page 44 | Population: Children aged 5 to 16]
If asthma is not diagnosed at this stage, the only additional investigation that offers
sensitivity without losing significant specificity is a bronchial challenge test. The
committee are aware that these tests are not easily available in many areas but reasoned
that making a positive recommendation should encourage services to improve access. They also noted that methacholine challenge is more sensitive than mannitol but did not
want to further limit the recommendation. Children aged 5 to 16
The committee noted that diagnostic testing is harder in children as they may find some
tests difficult to perform and be unwilling to have blood tests. A separate health economic model was developed for children using children-specific
diagnostic accuracy data and inputs. In children, testing for sensitisation to house dust
mite via skin prick test or finding an elevated IgE both showed high sensitivity. Therefore,
the diagnostic strategy was a rule-in–rule-out approach. This proved to be the most costeffective in children as it considerably reduced the proportion of children reaching the last
stage and needing an expensive bronchial challenge test. The committee agreed that a cheap and highly specific test was needed first to rule in
asthma. FeNO is a more acceptable first test in children than an eosinophil count because
it avoids the need to take blood, and because a level of 35 ppb or more is reasonably
specific for asthma in the presence of a suggestive history. The model suggested that a sensitive test should come next to rule out asthma. However,
the committee noted that some children would not be able to have a FeNO test because
the equipment is not available in all primary care settings, or because a minority may not
be able to perform the necessary expiratory manouevre. They were also concerned that
an increasing proportion of children with asthma are non-atopic and therefore unlikely to
have a raised FeNO level. However, these children may show bronchodilator reversibility
(BDR). It was therefore agreed that it would be appropriate to use spirometry with BDR as
a second test for those without an elevated FeNO, or as the first test in those in whom
FeNO could not be measured. Although this does not follow our optimal model exactly,
including BDR at this stage is still cost-effective. In children with a suggestive history of asthma, both skin prick testing for sensitisation to
house dust mite and measurement of total IgE are sensitive tests, and the committee
agreed that one or the other should be done next. If the test is negative, asthma is highly
Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights). Page 44 of
64

---

Evidence 4 [NICE NG245 | Section general | Recommendation general | Page 46 | Population: Children under 5]
In view of the difficulty in diagnosing asthma in this age group the committee also agreed
that any child who had been admitted to hospital, or been taken to the emergency
department twice or more, because of wheezing or breathlessness should be referred to a
specialist respiratory paediatrician for advice on diagnosis and management. How the recommendations might affect practice
The diagnostic tests recommended for both children and adults are not routinely carried
out in current practice, with the exception of spirometry and reversibility testing, which is
performed in some adults with suspected asthma. FeNO equipment is not available in
some areas, but an eosinophil count and IgE level is easily obtainable everywhere. Bronchial challenge tests are not done in primary care and infrequently used in secondary
care. The recommendations will increase the demand for challenge tests and initially there
will be a capacity problem. Incorporating the recommended diagnostic sequences into
clinical practice would therefore require significant investment. However, using the tests
increases the accuracy of asthma diagnosis and will be cost-effective over time. The recommendations for children under 5 are based on a pragmatic trial of treatment, as
is current practice. Return to recommendations
Monitoring asthma control
Recommendations

---

Evidence 5 [NICE NG245 | Section general | Recommendation general | Page 43 | Population: Children under 5]
Cut-offs of 50 ppb in adults and 35 ppb in children were agreed. No evidence was available for diagnostic tests in children under 5. The age at which a
child can co-operate with tests will vary, but the committee agreed that it is usually
necessary to manage these children pragmatically based on symptoms and signs only. Adults
Several tests showed good specificity for asthma, with values over 80% for blood
eosinophils, FeNO (cut-off values 40-50 ppb), peak expiratory flow (PEF) variability,
bronchial challenge tests, and spirometry with bronchodilator reversibility. However,
sensitivity was poor for most of these, and only FeNO and bronchial challenge tests
showed values over 70%. Although bronchial challenge is the most accurate test, overall, it
is more costly than others and is less readily available. Using the health economic model, the most cost-effective diagnostic strategy was found
to be a gradual rule-in approach. It facilitates a positive diagnosis of asthma in a broad
population using relatively inexpensive tests and confines the more expensive bronchial
challenge tests to the end of the sequence. The committee agreed that a cheap and highly specific test to rule in asthma should start
the sequence. This should be either an eosinophil count or a FeNO measurement, but both
need care in interpretation. For example, a raised eosinophil count can occur for other
reasons including other allergic diseases, and FeNO is also affected by allergic diseases,
although only those that affect the airways. Both measurements are altered in smokers. However, if used correctly in the presence of a history suggesting asthma, they are good
rule-in tests. The second test in the sequence should be to measure spirometry with reversibility. This is
a more specific test than it is sensitive, but it represents a test of airway function to
complement a first test which reflects atopy and so both components of asthma will have
been assessed. The committee were aware that there can be delays in accessing spirometry and FeNO
testing, and it is hoped that access will improve. However, if these tests are not available
or there is a significant delay in obtaining them, the committee agreed it would be
reasonable to use PEF variability as a substitute rule-in test. Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights). Page 43 of
64

---

Evidence 6 [NICE NG245 | Section general | Recommendation general | Page 53 | Population: Adults, young people and children (age-specific recommendations apply)]
adverse outcomes is relatively high and a referral to an asthma specialist for further
assessment and management is appropriate. If control is inadequate but neither FeNO nor eosinophil count is raised, the committee
considered the possible options to be the addition of either a leukotriene receptor
antagonist (LTRA) or a long-acting muscarinic receptor antagonist (LAMA). Evidence was
available looking at the addition of either an LTRA or a LAMA to baseline treatment with
moderate-dose ICS or moderate-dose ICS/LABA, but the 2 options were only compared
directly in 2 small studies. Although the comparison showed a reduction in exacerbations
with a LAMA compared with an LTRA, the committee did not have much confidence in the
result because of the small study population. They noted that it would be simpler to add
an LTRA than a LAMA because the latter would involve needing to teach the person with
asthma how to use an additional inhaler device, and the need for 2 inhalers is also less
environmentally desirable. An LTRA is also cheaper, but there is a risk of significant side
effects, particularly neuropsychiatric disturbances. It was agreed that there was no
convincing reason to recommend one option over the other and that the person with
asthma should decide which should be tried first after a discussion of the potential
benefits and harms. If these medicines have been tried and the person's asthma continues to be inadequately
controlled, further treatment is available using a variety of biologic agents. Use of these
falls outside the scope of this guideline and requires specialist assessment. The committee
therefore recommended that a referral should be made at this stage. How the recommendations might affect practice
The recommendations for increasing treatment are different from current standard
practice, but they apply to people with a new diagnosis of asthma. People with an existing
diagnosis of asthma who are stable on their current therapy do not have to switch
treatment. People on current pathways who need an increase in treatment will be switched
to MART, but this is one of the current options. There should therefore not be significant
disruption to asthma care. The new treatment steps are cost-effective for the NHS and in
particular will reduce the number of exacerbations requiring treatment and the number of
hospital admissions for asthma. Return to recommendations
Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights). Page 53 of
64

SOURCES

[NICE NG245, Section general, Recommendation general, p.42]
[NICE NG245, Section general, Recommendation general, p.48]
[NICE NG245, Section general, Recommendation general, p.44]
[NICE NG245, Section general, Recommendation general, p.46]
[NICE NG245, Section general, Recommendation general, p.43]
[NICE NG245, Section general, Recommendation general, p.53]

================================================================================
QUESTION 12
================================================================================
If spirometry is delayed, what alternative measurement can be taken over a two-week period to help confirm asthma?

Safety: {'red_flags_detected': [], 'in_scope': True, 'scope': 'Allergic Diseases → Asthma', 'population': 'Adults, young people and children (age-specific recommendations apply)'}

ANSWER / EVIDENCE

LLM generation is disabled. The following NICE NG245 guideline evidence was retrieved for the query:Evidence 1 [NICE NG245 | Section general | Recommendation general | Page 42 | Population: Adults]
similar information to a preceding one. Practical aspects were taken into account using the
committee's knowledge and experience. These included the availability of the tests, which
varies considerably (in particular, bronchial challenge testing is not available in primary
care and not readily available in secondary care), the ability of people to perform the tests,
and the acceptability of the tests to the person, which is particularly relevant in younger
children. The committee also considered the cost of the available tests. However, no health
economic study on the most cost-effective sequence or combination of tests was
identified. Therefore, a health economic model was developed to help address this. The committee discussed what cut-off values should be recommended for the tests. For
some of the tests it was agreed that it was inappropriate to state a numerical value for an
abnormal result. For example, normal ranges for blood tests may vary slightly between
laboratories. Therefore, for eosinophil counts and IgE levels, a raised measurement
(suggesting asthma) should be regarded as one above the upper end of the local
reference range. There are also several standardised methods of performing bronchial
challenge tests, and the definition of bronchial hyperresponsiveness will be dependent on
the method used. Spirometry should always be performed using an international standard protocol but the
method of expressing reversibility after bronchodilator varies. Ideally this would be based
on change in z-scores, but these are not measured by all spirometry equipment. Change in
absolute values of FEV1 is arguably best given as the percentage change compared with
the person's predicted FEV1, and using this parameter a change of 10% or more is
abnormal. Using the more traditional means of expressing the change as a percentage of
the baseline FEV1, increased reversibility would be 12% or more in adults and children. In
adults, the change should also be 200 ml or more. The committee agreed to include both
ways of measuring reversibility in its recommendations. An optimal cut-off value is also difficult to give for FeNO (fractional exhaled nitric oxide). There is good evidence that FeNO levels increase with age and with height, and ideally
normal ranges would be available which correct for these factors. However, there are
currently no standard charts and FeNO equipment does not give an age/height corrected
output. Although not ideal, the committee agreed that they need to suggest a simple cutoff value. And because FeNO is the first, and possibly the only, test in the recommended
sequences in both adults and children they agreed that the value should be reasonably
high so that it would be specific, acknowledging that this sacrifices a degree of sensitivity.

---

Evidence 2 [NICE NG245 | Section 1.2.3 | Recommendation 1.2.4 | Page 10 | Population: Children aged 5 to 16]
1.2.4
If asthma is not confirmed by eosinophil count, FeNO, BDR or PEF variability but

In [23]:
# Test Questions 16-20: Questions outside the provided guideline

questions = [
    "What is the prevalence of asthma in Egypt?",

    "What is the average annual cost of asthma treatment per patient?",

    "Which asthma inhaler brand is the most prescribed worldwide?",

    "What percentage of asthma patients in the United States are hospitalized each year?",

    "What is the average age of asthma diagnosis worldwide?"
]

for i, user_query in enumerate(questions, 16):

    print("\n" + "=" * 80)
    print(f"QUESTION {i}")
    print("=" * 80)
    print(user_query)

    safety = safety_check(user_query)
    print("\nSafety:", safety)

    if safety["red_flags_detected"]:
        print(
            "\n⚠️ Red-flag language detected. "
            "The query should be handled with appropriate clinical urgency."
        )

    demo = answer_query(user_query, use_llm=USE_LLM)

    print("\nANSWER / EVIDENCE\n")
    print(demo["answer"])

    if demo["sources"]:
        print("\nSOURCES\n")
        for r in demo["sources"]:
            print(citation_for(r))

================================================================================
QUESTION 16
================================================================================
What is the prevalence of asthma in Egypt?

Safety: {'red_flags_detected': [], 'in_scope': True, 'scope': 'Allergic Diseases → Asthma', 'population': 'Adults, young people and children (age-specific recommendations apply)'}

ANSWER / EVIDENCE

LLM generation is disabled. The following NICE NG245 guideline evidence was retrieved for the query:Evidence 1 [NICE NG245 | Section general | Recommendation general | Page 61 | Population: Adults, young people and children (age-specific recommendations apply)]
Context
The NICE guideline on asthma was published in 2017 and BTS/SIGN last updated their
asthma guideline in 2019. The guidelines overlap in the clinical areas included, and
healthcare practitioners in the UK have been using both sets of guidance. However, these guidelines differ in their approach to diagnosis. Concern has been raised
about the recommendations to use fractional exhaled nitric oxide (FeNO) measurement
and spirometry more widely, contained in NICE guidance. Likewise, there are significant
differences in several aspects of the treatment approach in each. BTS, NICE and SIGN
agreed that updating and unifying current guidance would be helpful for healthcare
professionals. This update to national asthma guidelines is timely for people with asthma and their
healthcare teams. There have been various initiatives that aim to improve outcomes for
people with asthma in the UK, but outcomes nevertheless remain poor. Mortality from
asthma continues to increase in the UK, and it remains a leading cause of morbidity. According to the Office for National Statistics, there were more than 1,400 asthma deaths
in the UK in 2018, an increase of 8% compared with 2017. For outcomes to improve, people
with asthma need excellent, evidence-based care. There are many uncertainties about the best way to diagnose, monitor and treat asthma. For example, there have been recent developments in our understanding of the value of
physiological tests. Also, there are new options for the use of inhaled corticosteroids and
what to do when treatment needs to be stepped up or down. The evidence in these areas
of uncertainty has been reviewed and the relevant recommendations updated. Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights). Page 61 of
64

---

Evidence 2 [NICE NG245 | Section 1.3 | Recommendation general | Page 13 | Population: Children under 5]
1.3 Diagnosing asthma in children under 5
Diagnosis is hard in this age group because it is difficult to do the tests and there are no
good reference standards.

---

Evidence 3 [NICE NG245 | Section 1.13 | Recommendation 1.13.1 | Page 28 | Population: Adolescents]
1.13.1
Discuss future career choices with adolescents with asthma and highlight
occupations that might increase susceptibility to work-related asthma symptoms.
[BTS/SIGN 2019]

---

Evidence 4 [NICE NG245 | Section 1.5 | Recommendation 1.5.1 | Page 14 | Population: Adults, young people and children (age-specific recommendations apply)]
1.5.1
Monitor asthma control at every review. In addition to asking about symptoms,
check:
• time off work or school due to asthma
• amount of reliever inhaler used, including a check of the prescription record
• number of courses of oral corticosteroids
• any admissions to hospital or attendance at an emergency department due
to asthma.
If control is suboptimal, see recommendation

---

Evidence 5 [NICE NG245 | Section 1.2.2 | Recommendation 1.2.3 | Page 10 | Population: Adults, young people and children (age-specific recommendations apply)]
1.2.3
If spirometry is not available or it is delayed, measure peak expiratory flow (PEF)
twice daily for 2 weeks. Diagnose asthma if PEF variability (expressed as
amplitude percentage mean) is 20% or more. [BTS/NICE/SIGN 2024]

---

Evidence 6 [NICE NG245 | Section general | Recommendation 1.1.4 | Page 9 | Population: Adults, young people and children (age-specific recommendations apply)]
1.1.4
Examine people with suspected asthma to identify expiratory polyphonic wheeze
and signs of other causes of respiratory symptoms but be aware that even if
examination results are normal, the person may still have asthma. [NICE 2017]
Initial treatment and objective tests for acute symptoms at
presentation

SOURCES

[NICE NG245, Section general, Recommendation general, p.61]
[NICE NG245, Section 1.3, Recommendation general, p.13]
[NICE NG245, Section 1.13, Recommendation 1.13.1, p.28]
[NICE NG245, Section 1.5, Recommendation 1.5.1, p.14]
[NICE NG245, Section 1.2.2, Recommendation 1.2.3, p.10]
[NICE NG245, Section general, Recommendation 1.1.4, p.9]

================================================================================
QUESTION 17
================================================================================
What is the average annual cost of asthma treatment per patient?

Safety: {'red_flags_detected': [], 'in_scope': True, 'scope': 'Allergic Diseases → Asthma', 'population': 'Adults, young people and children (age-specific recommendations apply)'}

ANSWER / EVIDENCE

LLM generation is disabled. The following NICE NG245 guideline evidence was retrieved for the query:Evidence 1 [NICE NG245 | Section general | Recommendation general | Page 39 | Population: Adults]
4 Inhalers
Can digital inhaler monitors cost-effectively improve adherence to preventer inhalers for
people with asthma? Does this improve asthma control and who would benefit most from
this intervention? [BTS/NICE/SIGN 2024]
For a short explanation of why the committee made this recommendation for
research, see the rationale and impact section on digital inhalers. Full details of the evidence and the committee's discussion are in evidence review R:
smart inhalers. 5 Monitoring inhaler technique
What is the current frequency and the current method being used to check the inhaler
technique of people with asthma? What is the optimal frequency and the best method of
checking inhaler technique to improve clinical outcomes for people with asthma? [NICE
2017]
6 Monitoring asthma control using telehealthcare
What is the long-term (more than 12 months) clinical and cost-effectiveness of using
telehealthcare as a means to monitor asthma control in adults, young people and children? Methods of telehealthcare can include telephone interview (with healthcare professional
involvement) and internet or smartphone-based monitoring support (no healthcare
professional involvement). [NICE 2017]
7 Decreasing pharmacological treatment
In adults, young people and children with well-controlled asthma, what are the objective
measurements and prognostic factors that indicate that a decrease in regular maintenance
treatment is appropriate? [NICE 2017]
8 Improving adherence to asthma medication
What are the most clinically and cost-effective strategies to improve medicines adherence
Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights). Page 39 of
64

---

Evidence 2 [NICE NG245 | Section general | Recommendation general | Page 48 | Population: Adults]
circumstances. FeNO
The evidence showed that, in both adults and children, regular FeNO monitoring led to a
reduction in the number of asthma exacerbations. In children there was also a significant
improvement in lung function. In adults, the reduction in exacerbations was achieved
alongside an overall reduction in the dosage of maintenance ICS therapy. This was not the
case in children, but the studies in this age group were more likely to be conducted in
secondary or tertiary care, so it is likely that they had a higher maintenance therapy
requirement. The committee concluded that FeNO monitoring was cost-effective in adults but may not
be in children. It was not possible on the current evidence to say what the optimum
frequency of monitoring should be, but the committee agreed that an appropriate
opportunity would be to make a routine measurement at the person's regular review
(which will be an annual review for most people). The FeNO level is a proxy measure of airway inflammation. It can therefore be very useful
in determining how to adjust treatment, or as an indicator of treatment adherence, when a
person with asthma has poor symptom control. Conversely, when symptom control is
excellent and the possibility of reducing maintenance therapy arises, a normal FeNO level
provides helpful reassurance. The committee therefore agreed that a FeNO measurement
should be considered whenever a change in maintenance therapy might be appropriate. How the recommendations might affect practice
Asthma control questionnaires are already recommended as part of an annual review. Therefore, no change to practice is anticipated. The recommendations on pulmonary
function are expected to reduce the use of PEF monitoring. Measurement of FeNO is increasingly used in secondary care asthma clinics, but in
primary care only a minority of GP practices have on-site access to the test. Regular FeNO
monitoring represents a significant change in practice because most people with asthma
are managed in primary care. This change will also carry a cost. The committee noted that
FeNO measurement is also useful in diagnosing asthma (see section 1.2 on objective tests
for diagnosing asthma), and increased access to the test will therefore be of dual benefit. Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights). Page 48 of
64

---

Evidence 3 [NICE NG245 | Section general | Recommendation 1.14.5 | Page 58 | Population: Adults]
1.14.5
Why the committee made the recommendation
The evidence for children and young people found that increasing the dose of ICS when
asthma control deteriorates did not result in any benefits or harms compared with the
usual dose in terms of reducing subsequent asthma exacerbations. It was limited to only 1
study with a small number of participants who had a personalised action plan. The
committee also looked at studies in adults, but they agreed that the evidence was not
applicable because of the high average age of participants.
The committee discussed the importance of a personalised action plan to guide children
and young people if their asthma worsens and to reassure them that they are in control of
their treatment. Children and young people who find that increasing their dose of ICS is
helpful when their asthma control worsens should be able to continue to do this as an
agreed strategy in their action plan. However, based on their experience, the committee
members agreed that it is important to review the child or young person's selfmanagement plan if their asthma control is deteriorating. Reviews involve checking current
medicines and inhaler technique, discussing any factors that may be triggering symptoms,
discussing adherence and education needs, and reviewing their action plan. They should
be carried out as needed, in addition to annual review.
The committee discussed the importance of an individualised approach for children and
young people, because they have varied and changing support needs at different ages.
Studies have shown that most child asthma deaths involve children who have frequent but
mild symptoms that are not responding to management in their personalised action plan.
Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights).
Page 58 of
64

---

Evidence 4 [NICE NG245 | Section general | Recommendation general | Page 36 | Population: Children aged 5 to 11]
Recommendations for research
The guideline committee has made the following recommendations for research. Key recommendations for research
1 Medicines for initial management
What is the clinical and cost-effectiveness of regular 'fixed-dose' inhaled corticosteroid
(ICS) regimens (using SABA [short-acting beta2 agonist] as a reliever) compared with 'asneeded' strategies (for example ICS/formoterol) as the initial standard treatment for
asthma in children aged 5 to 11 years? [BTS/NICE/SIGN 2024]
For a short explanation of why the committee made this recommendation for
research, see the rationale and impact section on medicines for initial management in
children aged 5 to 11. Full details of the evidence and the committee's discussion are in evidence review P:
drug classes for initial asthma management. 2 Medicine combination and sequencing
What is the best step-up treatment for people whose asthma is not controlled on a
combination inhaler of ICS plus formoterol used as needed? [BTS/NICE/SIGN 2024]
For a short explanation of why the committee made this recommendation for
research, see the rationale and impact section on medicine combination and
sequencing in people aged 12 and over. Full details of the evidence and the committee's discussion are in evidence review Q:
drug combinations and sequencing for asthma management. Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights). Page 36 of
64

---

Evidence 5 [NICE NG245 | Section general | Recommendation general | Page 51 | Population: People aged 12 and over]
comparisons with both of the other treatment options. There were also fewer
exacerbations with ICS plus SABA than with SABA alone. Apart from the difference in
exacerbations, there were only small differences between outcomes when comparing ICS
plus SABA as needed with as-needed AIR, and the committee did not assess these as
clinically important. However, the evidence showed that use of ICS (either as-needed AIR
or regular low-dose ICS plus SABA as needed) produced consistently better outcomes
than SABA alone. Health economic data showed that treatment with as-needed AIR was cheaper than
regular ICS plus SABA as needed. The committee therefore concluded that combination
inhalers used as needed should be the preferred treatment in newly diagnosed asthma in
adults. However, there were concerns about the minority of people with asthma in whom
the diagnosis is first made because of an acute attack. In these particularly symptomatic
people, the committee agreed on safety grounds that initial treatment should be given
regularly and recommended starting the low-dose MART (maintenance and reliever
therapy) regimen. How the recommendations might affect practice
Most people aged 12 and over with newly diagnosed asthma are currently treated with
either a SABA alone or with regular ICS plus SABA as needed. The new recommendations
represent a significant change in practice. The use of combination inhalers is more
expensive than SABA alone, but cheaper than regular ICS plus SABA as needed. Therefore,
the cost impact will vary depending on the predominant form of treatment in each general
practice. However, there should be future savings from a reduction in severe asthma
exacerbations compared with either of the current treatment options. Return to recommendations
Medicine combination and sequencing in people
aged 12 and over
Recommendations

---

Evidence 6 [NICE NG245 | Section general | Recommendation general | Page 37 | Population: Adults]
3 Diagnostic pathways
What is the cost-effectiveness and feasibility of the proposed BTS/NICE/SIGN diagnostic
pathways for asthma in children and young people aged 5 and over and in adults aged 17
and over? [BTS/NICE/SIGN 2024]
Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights). Page 37 of
64

SOURCES

[NICE NG245, Section general, Recommendation general, p.39]
[NICE NG245, Section general, Recommendation general, p.48]
[NICE NG245, Section general, Recommendation 1.14.5, p.58]
[NICE NG245, Section general, Recommendation general, p.36]
[NICE NG245, Section general, Recommendation general, p.51]
[NICE NG245, Section general, Recommendation general, p.37]

================================================================================
QUESTION 18
================================================================================
Which asthma inhaler brand is the most prescribed worldwide?

Safety: {'red_flags_detected': [], 'in_scope': True, 'scope': 'Allergic Diseases → Asthma', 'population': 'Adults, young people and children (age-specific recommendations apply)'}

ANSWER / EVIDENCE

LLM generation is disabled. The following NICE NG245 guideline evidence was retrieved for the query:Evidence 1 [NICE NG245 | Section general | Recommendation general | Page 39 | Population: Adults]
4 Inhalers
Can digital inhaler monitors cost-effectively improve adherence to preventer inhalers for
people with asthma? Does this improve asthma control and who would benefit most from
this intervention? [BTS/NICE/SIGN 2024]
For a short explanation of why the committee made this recommendation for
research, see the rationale and impact section on digital inhalers. Full details of the evidence and the committee's discussion are in evidence review R:
smart inhalers. 5 Monitoring inhaler technique
What is the current frequency and the current method being used to check the inhaler
technique of people with asthma? What is the optimal frequency and the best method of
checking inhaler technique to improve clinical outcomes for people with asthma? [NICE
2017]
6 Monitoring asthma control using telehealthcare
What is the long-term (more than 12 months) clinical and cost-effectiveness of using
telehealthcare as a means to monitor asthma control in adults, young people and children? Methods of telehealthcare can include telephone interview (with healthcare professional
involvement) and internet or smartphone-based monitoring support (no healthcare
professional involvement). [NICE 2017]
7 Decreasing pharmacological treatment
In adults, young people and children with well-controlled asthma, what are the objective
measurements and prognostic factors that indicate that a decrease in regular maintenance
treatment is appropriate? [NICE 2017]
8 Improving adherence to asthma medication
What are the most clinically and cost-effective strategies to improve medicines adherence
Asthma: diagnosis, monitoring and chronic asthma management (BTS, NICE, SIGN)
(NG245)
© NICE 2026. All rights reserved. Subject to Notice of rights (https://www.nice.org.uk/terms-andconditions#notice-of-rights). Page 39 of
64

---

Evidence 2 [NICE NG245 | Section general | Recommendation 1.6.3 | Page 49 | Population: Adults]
1.6.3
Why the committee made the recommendations
The evidence review showed that clinical outcomes were poorest in all age groups with
asthma when using SABA (short-acting beta2 agonist) alone. The committee also took into
account other evidence from several sources, including national reviews of asthma deaths
in both adults and children, which highlighted the dangers of using SABA without ICS in
people with asthma. They therefore recommended that SABA alone should not be used in
people with a diagnosis of asthma.
The previous NICE and BTS/SIGN guidelines had recommended a number of actions which
should be taken before increasing treatment, and the committee agreed by consensus that
a FeNO check should also be done as long as the equipment is available to do this.
How the recommendations might affect practice